version: "3.9"

services:
  db:
    image: postgres:16
    container_name: nflmockdraftsim-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: nfldb
    volumes:
      - ./PlayerData:/csv
